[2024-10-14T22:00:10.763+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.transform_data_dashboard scheduled__2024-10-14T21:00:00+00:00 [queued]>
[2024-10-14T22:00:10.773+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.transform_data_dashboard scheduled__2024-10-14T21:00:00+00:00 [queued]>
[2024-10-14T22:00:10.773+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-14T22:00:10.782+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): fetch_tranform_data.transform_data_dashboard> on 2024-10-14 21:00:00+00:00
[2024-10-14T22:00:10.794+0000] {standard_task_runner.py:60} INFO - Started process 245 to run task
[2024-10-14T22:00:10.796+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_get_weather_data', 'fetch_tranform_data.transform_data_dashboard', 'scheduled__2024-10-14T21:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_weather.py', '--cfg-path', '/tmp/tmp7ga967x1']
[2024-10-14T22:00:10.797+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask fetch_tranform_data.transform_data_dashboard
[2024-10-14T22:00:10.810+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-14T22:00:10.842+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_get_weather_data.fetch_tranform_data.transform_data_dashboard scheduled__2024-10-14T21:00:00+00:00 [running]> on host ee2b315f6b67
[2024-10-14T22:00:10.907+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_get_weather_data' AIRFLOW_CTX_TASK_ID='fetch_tranform_data.transform_data_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T21:00:00+00:00'
[2024-10-14T22:00:10.925+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_get_weather.py", line 121, in transform_data_dashboard
    transform_data_into_csv(n_files, filename='data.csv')
  File "/opt/airflow/dags/dag_get_weather.py", line 106, in transform_data_into_csv
    'temperature': data_city['main']['temp'],
TypeError: string indices must be integers
[2024-10-14T22:00:10.931+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_get_weather_data, task_id=fetch_tranform_data.transform_data_dashboard, execution_date=20241014T210000, start_date=20241014T220010, end_date=20241014T220010
[2024-10-14T22:00:10.947+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task fetch_tranform_data.transform_data_dashboard (string indices must be integers; 245)
[2024-10-14T22:00:10.969+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-14T22:00:10.991+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
