[2024-10-14T21:22:24.030+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T21:22:24.035+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T21:22:24.036+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-14T21:22:24.043+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): fetch_tranform_data.fetch_and_save_weather> on 2024-10-14 20:00:00+00:00
[2024-10-14T21:22:24.050+0000] {standard_task_runner.py:60} INFO - Started process 240 to run task
[2024-10-14T21:22:24.053+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_get_weather_data', 'fetch_tranform_data.fetch_and_save_weather', 'scheduled__2024-10-14T20:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_weather.py', '--cfg-path', '/tmp/tmpxqz4q33t']
[2024-10-14T21:22:24.054+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask fetch_tranform_data.fetch_and_save_weather
[2024-10-14T21:22:24.063+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-14T21:22:24.087+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [running]> on host cc88bfa9cc01
[2024-10-14T21:22:24.133+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_get_weather_data' AIRFLOW_CTX_TASK_ID='fetch_tranform_data.fetch_and_save_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T20:00:00+00:00'
[2024-10-14T21:22:24.134+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_get_weather.py", line 58, in fetch_and_save_weather
    data = kwargs['data']
KeyError: 'data'
[2024-10-14T21:22:24.140+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_get_weather_data, task_id=fetch_tranform_data.fetch_and_save_weather, execution_date=20241014T200000, start_date=20241014T212224, end_date=20241014T212224
[2024-10-14T21:22:24.147+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task fetch_tranform_data.fetch_and_save_weather ('data'; 240)
[2024-10-14T21:22:24.185+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-14T21:22:24.220+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T21:51:22.531+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T21:51:22.538+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T21:51:22.538+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-14T21:51:22.546+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): fetch_tranform_data.fetch_and_save_weather> on 2024-10-14 20:00:00+00:00
[2024-10-14T21:51:22.553+0000] {standard_task_runner.py:60} INFO - Started process 161 to run task
[2024-10-14T21:51:22.556+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_get_weather_data', 'fetch_tranform_data.fetch_and_save_weather', 'scheduled__2024-10-14T20:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_weather.py', '--cfg-path', '/tmp/tmpz51v2n4v']
[2024-10-14T21:51:22.557+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask fetch_tranform_data.fetch_and_save_weather
[2024-10-14T21:51:22.566+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-14T21:51:22.609+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [running]> on host fd92e3be397d
[2024-10-14T21:51:22.687+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_get_weather_data' AIRFLOW_CTX_TASK_ID='fetch_tranform_data.fetch_and_save_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T20:00:00+00:00'
[2024-10-14T21:51:22.688+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_get_weather.py", line 60, in fetch_and_save_weather
    cities_list = json.loads(Variable.get("cities", default="[]"))
TypeError: get() got an unexpected keyword argument 'default'
[2024-10-14T21:51:22.694+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_get_weather_data, task_id=fetch_tranform_data.fetch_and_save_weather, execution_date=20241014T200000, start_date=20241014T215122, end_date=20241014T215122
[2024-10-14T21:51:22.706+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task fetch_tranform_data.fetch_and_save_weather (get() got an unexpected keyword argument 'default'; 161)
[2024-10-14T21:51:22.729+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-14T21:51:22.756+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T21:59:26.287+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T21:59:26.293+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T21:59:26.293+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-14T21:59:26.301+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): fetch_tranform_data.fetch_and_save_weather> on 2024-10-14 20:00:00+00:00
[2024-10-14T21:59:26.308+0000] {standard_task_runner.py:60} INFO - Started process 161 to run task
[2024-10-14T21:59:26.311+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_get_weather_data', 'fetch_tranform_data.fetch_and_save_weather', 'scheduled__2024-10-14T20:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_weather.py', '--cfg-path', '/tmp/tmpbt9fdt9l']
[2024-10-14T21:59:26.311+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask fetch_tranform_data.fetch_and_save_weather
[2024-10-14T21:59:26.322+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-14T21:59:26.379+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_get_weather_data.fetch_tranform_data.fetch_and_save_weather scheduled__2024-10-14T20:00:00+00:00 [running]> on host ee2b315f6b67
[2024-10-14T21:59:26.462+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_get_weather_data' AIRFLOW_CTX_TASK_ID='fetch_tranform_data.fetch_and_save_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T20:00:00+00:00'
[2024-10-14T21:59:27.053+0000] {logging_mixin.py:188} INFO - Successfully fetched data for paris
[2024-10-14T21:59:27.746+0000] {logging_mixin.py:188} INFO - Successfully fetched data for london
[2024-10-14T21:59:28.163+0000] {logging_mixin.py:188} INFO - Successfully fetched data for washington
[2024-10-14T21:59:28.165+0000] {logging_mixin.py:188} INFO - Weather data saved to /app/raw_files/2024-10-14 21:59.json
[2024-10-14T21:59:28.166+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-10-14T21:59:28.178+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_get_weather_data, task_id=fetch_tranform_data.fetch_and_save_weather, execution_date=20241014T200000, start_date=20241014T215926, end_date=20241014T215928
[2024-10-14T21:59:28.212+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-14T21:59:28.240+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
