[2024-10-14T22:04:32.129+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.transform_data_dashboard scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T22:04:32.134+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_get_weather_data.fetch_tranform_data.transform_data_dashboard scheduled__2024-10-14T20:00:00+00:00 [queued]>
[2024-10-14T22:04:32.134+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-10-14T22:04:32.143+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): fetch_tranform_data.transform_data_dashboard> on 2024-10-14 20:00:00+00:00
[2024-10-14T22:04:32.149+0000] {standard_task_runner.py:60} INFO - Started process 427 to run task
[2024-10-14T22:04:32.152+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_get_weather_data', 'fetch_tranform_data.transform_data_dashboard', 'scheduled__2024-10-14T20:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_weather.py', '--cfg-path', '/tmp/tmp6q6eyd9a']
[2024-10-14T22:04:32.152+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask fetch_tranform_data.transform_data_dashboard
[2024-10-14T22:04:32.161+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-14T22:04:32.184+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_get_weather_data.fetch_tranform_data.transform_data_dashboard scheduled__2024-10-14T20:00:00+00:00 [running]> on host ee2b315f6b67
[2024-10-14T22:04:32.230+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_get_weather_data' AIRFLOW_CTX_TASK_ID='fetch_tranform_data.transform_data_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T20:00:00+00:00'
[2024-10-14T22:04:32.241+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_get_weather.py", line 121, in transform_data_dashboard
    transform_data_into_csv(n_files, filename='data.csv')
  File "/opt/airflow/dags/dag_get_weather.py", line 106, in transform_data_into_csv
    'temperature': data_city['main']['temp'],
TypeError: string indices must be integers
[2024-10-14T22:04:32.246+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_get_weather_data, task_id=fetch_tranform_data.transform_data_dashboard, execution_date=20241014T200000, start_date=20241014T220432, end_date=20241014T220432
[2024-10-14T22:04:32.253+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task fetch_tranform_data.transform_data_dashboard (string indices must be integers; 427)
[2024-10-14T22:04:32.283+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-14T22:04:32.312+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
